/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DietRecord {
  'id' : string,
  'userId' : string,
  'timestamp' : bigint,
  'dietPlan' : string,
}
export interface DrugInteractionRecord {
  'id' : string,
  'interactionSummary' : string,
  'userId' : string,
  'medications' : Array<string>,
  'timestamp' : bigint,
}
export interface HospitalRecord {
  'id' : string,
  'userId' : string,
  'results' : string,
  'timestamp' : bigint,
  'location' : string,
}
export interface MedicationReminder {
  'id' : string,
  'dosage' : string,
  'userId' : string,
  'isActive' : boolean,
  'reminderTime' : bigint,
  'medicineName' : string,
}
export interface Prescription {
  'id' : string,
  'analysisResult' : string,
  'userId' : string,
  'extractedText' : string,
  'timestamp' : bigint,
}
export interface PriceRecord {
  'id' : string,
  'userId' : string,
  'links' : string,
  'timestamp' : bigint,
  'medicineName' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReminder' : ActorMethod<[string, string, string, bigint], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePrescription' : ActorMethod<[string], boolean>,
  'deleteReminder' : ActorMethod<[string], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDietHistory' : ActorMethod<[string], Array<DietRecord>>,
  'getDrugInteractionHistory' : ActorMethod<
    [string],
    Array<DrugInteractionRecord>
  >,
  'getHospitalHistory' : ActorMethod<[string], Array<HospitalRecord>>,
  'getPrescriptionById' : ActorMethod<[string], [] | [Prescription]>,
  'getPrescriptions' : ActorMethod<[string], Array<Prescription>>,
  'getPriceHistory' : ActorMethod<[string], Array<PriceRecord>>,
  'getReminders' : ActorMethod<[string], Array<MedicationReminder>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDietRecommendation' : ActorMethod<[string, string], string>,
  'saveDrugInteractionResult' : ActorMethod<
    [string, Array<string>, string],
    string
  >,
  'saveHospitalSearch' : ActorMethod<[string, string, string], string>,
  'savePrescription' : ActorMethod<[string, string, string], string>,
  'savePriceComparison' : ActorMethod<[string, string, string], string>,
  'updateReminderStatus' : ActorMethod<[string, boolean], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];