/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const DietRecord = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Text,
  'timestamp' : IDL.Int,
  'dietPlan' : IDL.Text,
});
export const DrugInteractionRecord = IDL.Record({
  'id' : IDL.Text,
  'interactionSummary' : IDL.Text,
  'userId' : IDL.Text,
  'medications' : IDL.Vec(IDL.Text),
  'timestamp' : IDL.Int,
});
export const HospitalRecord = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Text,
  'results' : IDL.Text,
  'timestamp' : IDL.Int,
  'location' : IDL.Text,
});
export const Prescription = IDL.Record({
  'id' : IDL.Text,
  'analysisResult' : IDL.Text,
  'userId' : IDL.Text,
  'extractedText' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const PriceRecord = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Text,
  'links' : IDL.Text,
  'timestamp' : IDL.Int,
  'medicineName' : IDL.Text,
});
export const MedicationReminder = IDL.Record({
  'id' : IDL.Text,
  'dosage' : IDL.Text,
  'userId' : IDL.Text,
  'isActive' : IDL.Bool,
  'reminderTime' : IDL.Int,
  'medicineName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReminder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePrescription' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteReminder' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDietHistory' : IDL.Func([IDL.Text], [IDL.Vec(DietRecord)], ['query']),
  'getDrugInteractionHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DrugInteractionRecord)],
      ['query'],
    ),
  'getHospitalHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HospitalRecord)],
      ['query'],
    ),
  'getPrescriptionById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Prescription)],
      ['query'],
    ),
  'getPrescriptions' : IDL.Func([IDL.Text], [IDL.Vec(Prescription)], ['query']),
  'getPriceHistory' : IDL.Func([IDL.Text], [IDL.Vec(PriceRecord)], ['query']),
  'getReminders' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MedicationReminder)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDietRecommendation' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'saveDrugInteractionResult' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveHospitalSearch' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'savePrescription' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'savePriceComparison' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'updateReminderStatus' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const DietRecord = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Text,
    'timestamp' : IDL.Int,
    'dietPlan' : IDL.Text,
  });
  const DrugInteractionRecord = IDL.Record({
    'id' : IDL.Text,
    'interactionSummary' : IDL.Text,
    'userId' : IDL.Text,
    'medications' : IDL.Vec(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const HospitalRecord = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Text,
    'results' : IDL.Text,
    'timestamp' : IDL.Int,
    'location' : IDL.Text,
  });
  const Prescription = IDL.Record({
    'id' : IDL.Text,
    'analysisResult' : IDL.Text,
    'userId' : IDL.Text,
    'extractedText' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const PriceRecord = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Text,
    'links' : IDL.Text,
    'timestamp' : IDL.Int,
    'medicineName' : IDL.Text,
  });
  const MedicationReminder = IDL.Record({
    'id' : IDL.Text,
    'dosage' : IDL.Text,
    'userId' : IDL.Text,
    'isActive' : IDL.Bool,
    'reminderTime' : IDL.Int,
    'medicineName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReminder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePrescription' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteReminder' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDietHistory' : IDL.Func([IDL.Text], [IDL.Vec(DietRecord)], ['query']),
    'getDrugInteractionHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DrugInteractionRecord)],
        ['query'],
      ),
    'getHospitalHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HospitalRecord)],
        ['query'],
      ),
    'getPrescriptionById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Prescription)],
        ['query'],
      ),
    'getPrescriptions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Prescription)],
        ['query'],
      ),
    'getPriceHistory' : IDL.Func([IDL.Text], [IDL.Vec(PriceRecord)], ['query']),
    'getReminders' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MedicationReminder)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDietRecommendation' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'saveDrugInteractionResult' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveHospitalSearch' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'savePrescription' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'savePriceComparison' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'updateReminderStatus' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };